# Brew
# tap 'clojure/tools'
brew 'awscli'
brew 'bat'
brew 'borkdude/brew/babashka'
brew 'borkdude/brew/clj-kondo'
brew 'borkdude/brew/jet'
brew 'babashka/brew/neil'
brew 'cheat'
brew 'cloc'
brew 'clojure'
brew 'clojure-lsp/brew/clojure-lsp-native'
# brew 'csvkit'
brew 'difftastic'
brew 'eza'
brew 'fd'
brew 'ffmpeg'
brew 'figlet'
brew 'fzf'
brew 'gcc'
brew 'git'
brew 'glow'
# brew 'git-delta'
# brew 'grep'
brew 'imagemagick'
brew 'jq'
brew 'lame'
brew 'make'
# brew 'mit-scheme'
brew 'nvim'
brew 'ripgrep'
brew 'rlwrap'
brew 'sqlite'
brew 'terminal-notifier'
brew 'the_silver_searcher'
brew 'tree-sitter'
brew 'tree-sitter-cli'
brew 'tldr'
brew 'tmux'
brew 'tree'
brew 'youtube-dl'
brew 'zoxide'

# cask
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
# cask '1password'
# cask 'alfred'
cask 'arc'
# cask 'caffeine'
cask 'daisydisk'
cask 'docker'
cask 'font-liberation-mono-for-powerline'
# cask 'gpg-suite'
cask 'ghostty'
cask 'karabiner-elements'
cask 'telegram'
cask 'the-unarchiver'
cask 'transmission'
# cask 'zprint'
