---
- name: CL-Tools | Update Homebrew
  homebrew: update_homebrew=yes upgrade_all=yes

- name: CL-Tools | Homebrew taps
  homebrew_tap: name={{ item }} state=present
  with_items:
    - caskroom/cask
    - caskroom/fonts
    - caskroom/versions
    - homebrew/versions
    - neovim/neovim
    - thoughtbot/formulae

- name: CL-Tools | Install Homebrew packages
  homebrew: name={{ item }} state=present
  ignore_errors: true
  with_items:
    - ansible
    - awscli
    - cheat
    - ctags
    - elasticsearch17
    - emacs
    - ffmpeg
    - figlet
    - gcc
    - gifify
    - git
    - heroku
    - highlight
    - hub
    - imagemagick
    - jmeter
    - jpeg
    - keybase
    - lame
    - leiningen
    - lua
    - mit-scheme
    - neovim
    - node
    - openssl
    - openssl
    - phantomjs
    - pick
    - python
    - rbenv
    - rbenv-vars
    - reattach-to-user-namespace
    - rlwrap
    - ruby-build
    - the_silver_searcher
    - tmux
    - tree
    - wget
    - youtube-dl
    - zsh

- name: CL-Tools | Fonts
  homebrew_cask: name={{ item }} state=installed
  with_items:
    - font-liberation-mono-for-powerline

- name: Ensure ~/.antigen exists
  file: path={{ home }}/.antigen state=directory

- name: CL-Tools | Install Antigen
  get_url:
    url: https://cdn.rawgit.com/zsh-users/antigen/v1.2.0/bin/antigen.zsh
    dest: "{{ home }}/.antigen/antigen.zsh"
