---
- name: Dotfiles | Link dotfiles
  file: src=~/dotfiles/{{ item }}
        dest=~/{{ item }}
        state=link
  with_items:
    - .agignore
    - .aliases
    - .bash_profile
    - .bash_prompt
    - bin
    - .cheat
    - .clojure
    - .config
    - .ctags
    - .doom.d
    - .eslintrc.json
    - .functions
    - .gemrc
    - .gitconfig
    - .gitignore_global
    - .hammerspoon
    - .lein
    - .osx
    - .psqlrc
    - .sqliterc
    - .tmux.conf
    - .vim
    - .vimrc
    - .zsh
    - .zshrc
