---
- name: Packages | Update Homebrew
  community.general.homebrew: update_homebrew=yes upgrade_all=yes

- name: Packages | Homebrew taps
  community.general.homebrew_tap: name={{ item }} state=present
  with_items: "{{ homebrew_taps }}"

- name: Packages | Cask taps
  community.general.homebrew_tap: name={{ item }} state=present
  with_items: "{{ cask_taps }}"

- name: Packages | Install Homebrew packages
  community.general.homebrew: name={{ item }} state=present
  with_items: "{{ homebrew_packages }}"
  ignore_errors: true

- name: Packages | Install Casks
  community.general.homebrew_cask: name={{ item }} state=installed
  with_items: "{{ cask_apps }}"
  ignore_errors: true

- name: Packages | Fonts
  community.general.homebrew_cask: name={{ item }} state=installed
  with_items:
    - font-liberation-mono-for-powerline

# - name: Packages | Ensure ~/.antigen exists
#   file: path={{ home }}/.antigen state=directory

# Using brew
# - name: Packages | Install Antigen
#   get_url:
#     url: https://cdn.rawgit.com/zsh-users/antigen/v1.2.0/bin/antigen.zsh
#     dest: "{{ home }}/.antigen/antigen.zsh"

- name: Packages | Configure vim
  command: vim +PluginInstall +qall
