---
- name: Shell | Ensure {{ shell }} is in /etc/shells
  lineinfile: dest=/etc/shells line={{ shell }} state=present owner=root group=wheel mode=0644
  become: yes

- name: Shell | Checking for current user shell
  shell: dscl . read ~ UserShell | awk '{print $2}'
  register: osx_login_shell_current_login_shell
  changed_when: false

- name: Shell | Making zsh active shell
  become: yes
  user:
    name: "{{ user }}"
    shell: "{{ shell }}"
  when: osx_login_shell_current_login_shell.stdout != "{{ shell }}"
