---
- hosts: localhost
  user: "{{ lookup('env', 'USER') }}"
  become: yes
  connection: local
  tasks:
    # - include: tasks/shell.yml
    # - include: tasks/editors.yml
    - include: tasks/dotfiles.yml
    # - include: tasks/osx_defaults.yml
  vars_files:
    - vars.yml
  vars:
    shell: "/usr/local/bin/zsh"
    user: "{{ lookup('env','USER') }}"
    home: "{{ lookup('env','HOME') }}"
