---
- hosts: localhost
  user: "{{ lookup('env', 'USER') }}"
  connection: local
  tasks:
    - include: tasks/packages.yml
    - include: tasks/databases.yml
    - include: tasks/dotfiles.yml
    - include: tasks/shell.yml
    - include: tasks/config.yml
  vars_files:
    - vars.yml
  vars:
    shell: "/usr/local/bin/zsh"
    home: "{{ lookup('env','HOME') }}"
